# Root-level config.toml

[project]
name = "covid-19-drug-discovery"
version = "1.0.0"
description = "Bioactivity prediction using multi-task neural networks and stacking classifiers"
authors = ["Sohila Osama <sohilaosama1661@gmail.com>"]

[dependencies]
python = "3.10"
pandas = "latest"
numpy = "latest"
tensorflow = "latest"
keras = "latest"
joblib = "1.3.2"
streamlit = "latest"
scikit-learn = "latest"
rdkit = "2022.9.5"

[environment]
conda_env = "environment.yml"
streamlit_config = ".streamlit/config.toml"

[deployment]
platform = "streamlit-cloud"
