name: covid-19-drug-discovery
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  
  - rdkit=2022.9.5  # Ensure the exact version compatible with your Python version
  - pandas
  - numpy
  - tensorflow
  - keras==3.8.0
  - joblib
  - streamlit
  - scikit-learn
